<?php

namespace app\models\admin;

use Yii;
use yii\db\ActiveRecord;

class AdminLoginForm extends ActiveRecord
{
    /*
     * 表名
     */
    public static function tableName()
    {
        return 'user'; // TODO: Change the autogenerated stub
    }

    /*
     * 规则
     */
    public function rules()
    {
        return[
            [['username','password'],'required'],
            ['password','validatePassword']
        ];
    }

    /*
     * 验证密码
     */
    public function validatePassword()
    {
        if (!$this->hasErrors()) {
            $data = self::find()
                ->where(['username' => $this->username])
                ->andwhere(['password' => $this->password])
                ->one();
            if (is_null($data)) {
                $this->addError('password', '用户名或密码错误');
            }
        }
    }

    public function login($data)
    {
        if ($this->load($data) && $this->validate()) {
            $session = Yii::$app->session;
            $session->open();
            $session->set('username', $this->username);
            $this->updateAll(['update_at' => time()], ['username' => $this->username]);
            return true;
        }
        return false;
    }

}